### ISSUE TITLE
android9.0 app界面SSID显示为<unknown ssid>点击配网后程序崩溃

### ISSUE THREAD

**Issue by gaokechen** [EspressifApp/EsptouchForAndroid#36]
`E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: com.shuichan, PID: 1405
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:355)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.NullPointerException: SSID can't be empty
        at com.espressif.iot.esptouch.EsptouchTask.<init>(EsptouchTask.java:62)
        at com.espressif.iot.esptouch.EsptouchTask.<init>(EsptouchTask.java:57)
        at com.shuichan.GKCAPP.Activity.WiFiSmartConfigActivity$EsptouchAsyncTask4.doInBackground(WiFiSmartConfigActivity.java:352)
        at com.shuichan.GKCAPP.Activity.WiFiSmartConfigActivity$EsptouchAsyncTask4.doInBackground(WiFiSmartConfigActivity.java:273)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
`

**Comment by gaokechen** [comment]
我试了一下Android 9需要授予位置权限后把GPS打开才能获取Wi-Fi信息
