### ISSUE TITLE
必现 send gc code 在华为mate30 pro Android10.0，emui 10.0

### ISSUE THREAD

**Issue by MuYuLinFeng** [EspressifApp/EsptouchForAndroid#55]
I/deviceconnsdk: [2020-03-06 15:29:56][INFO] MKIOT tcp_socket.c:106 tcp_bind_port errno: err_no: 98, strerr: Address already in use
V/AudioManager: querySoundEffectsEnabled...
E/stavix_app: [2020-03-06 15:30:02][ERRR] MKIOT :-995236249 [ (AddNewDeviceActivity.java:246)#replaceToCheckDmsResultFragment ] hml replaceFragment
D/Gabe: call	returning from cache
D/Gabe: call	returning from cache
__EsptouchTask: Welcome Esptouch v0.3.7.2
D/Gabe: call	returning from cache
UDPSocketServer: mServerSocket is created, socket read timeout: 120000, port: 18266
__EsptouchTask: execute()
__EsptouchTask: localInetAddress: /192.168.8.206
__EsptouchTask: send gc code 
D/__EsptouchTask: __listenAsyn() start
I/__EsptouchTask: expectOneByte: 24
D/UDPSocketServer: receiveSpecLenBytes() entrance: len = 11
I/deviceconnsdk: [2020-03-06 15:30:06][INFO] MKIOT tcp_socket.c:106 tcp_bind_port errno: err_no: 98, strerr: Address already in use
__EsptouchTask: send gc code 
__EsptouchTask: send gc code 
__EsptouchTask: send gc code 
I/deviceconnsdk: [2020-03-06 15:30:26][INFO] MKIOT tcp_socket.c:106 tcp_bind_port errno: err_no: 98, strerr: Address already in use
__EsptouchTask: send gc code 
__EsptouchTask: send gc code 
I/deviceconnsdk: [2020-03-06 15:30:36][INFO] MKIOT tcp_socket.c:106 tcp_bind_port errno: err_no: 98, strerr: Address already in use
__EsptouchTask: send gc code 
I/HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
D/deviceconnsdk: [2020-03-06 15:30:43][DEBG] MKIOT c_mrpc.c:436 0x78c49ee653 120.77.150.206 --> 120.77.150.206:5025 success
D/deviceconnsdk: [2020-03-06 15:30:44][DEBG] MKIOT c_mrpc.c:333 0x7943740800 heart beat comming
__EsptouchTask: send gc code 

E/ResMng NATIVE_MSG_FILTER: endActivityTransaction: margin state not match
V/FA: Recording user engagement, ms: 133817
D/HMSAgent: Activity(1351)->Application(473)->ActivityMgr(218)->onActivityPaused
.module.adddevice.scanandcreate.AddNewDeviceActivity@c796ace
V/FA: Using local app measurement service
E/ResMng NATIVE_MSG_FILTER: endActivityTransaction: margin state not match
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer: disableOutlineDraw is true
UDPSocketClient: USPSocketClient is interrupt
UDPSocketServer: USPSocketServer is interrupt
UDPSocketServer: mServerSocket is closed
W/System.err: java.net.SocketTimeoutException: Poll timed out
E/ResMng NATIVE_MSG_FILTER: endActivityTransaction: margin state not match
E/stavix_app: [2020-03-06 15:32:02][ERRR] MKIOT :-995236249 [ (DeviceSettingActivity.java:389)#onActivityResult ] requestCode :1079  resultCode:0
V/FA: Activity paused, time: 2374725309
W/System.err:     at libcore.io.IoBridge.poll(IoBridge.java:682)
W/System.err:     at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:150)
W/System.err:     at java.net.PlainDatagramSocketImpl.receive0(PlainDatagramSocketImpl.java:141)
W/System.err:     at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:164)
W/System.err:     at java.net.DatagramSocket.receive(DatagramSocket.java:847)
W/System.err:     at com.espressif.iot.esptouch.udp.UDPSocketServer.receiveSpecLenBytes(UDPSocketServer.java:110)
W/System.err:     at com.espressif.iot.esptouch.task.__EsptouchTask$1.run(__EsptouchTask.java:165)
I/__EsptouchTask: receive rubbish message, just ignore
D/FA: Event not sent since app measurement is disabled
D/__EsptouchTask: __listenAsyn() finish
D/ZrHung.AppEyeUiProbe: not watching, wait.

**Comment by XuXiangJun** [comment]
我们这边用 p30(Android 10) 测试下来没有问题
你们用的是我们的 APP 吗？
设备用的是 Esp32 还是 Esp8266？

**Comment by MuYuLinFeng** [comment]
你好：
我用的这个github的demo测试的 
硬件是8266EX

**Comment by afunx** [comment]
Address already in use
端口已被占用

**Comment by MuYuLinFeng** [comment]
> Address already in use
> 端口已被占用
请问默认的参数如下 这些参数我是否可以更改？有没有一定的修改规则？
    public EsptouchTaskParameter() {
        mIntervalGuideCodeMillisecond = 8;
        mIntervalDataCodeMillisecond = 8;
        mTimeoutGuideCodeMillisecond = 2000;
        mTimeoutDataCodeMillisecond = 4000;
        mTotalRepeatTime = 1;
        mEsptouchResultOneLen = 1;
        mEsptouchResultMacLen = 6;
        mEsptouchResultIpLen = 4;
        mEsptouchResultTotalLen = 1 + 6 + 4;
        mPortListening = 18266;
        mTargetPort = 7001;
        mWaitUdpReceivingMilliseond = 15000;
        mWaitUdpSendingMillisecond = 45000;
        mThresholdSucBroadcastCount = 1;
        mExpectTaskResultCount = 1;
    }

**Comment by Rairmmd** [comment]
有解决办法吗？遇到同样的问题

**Comment by MuYuLinFeng** [comment]
> 有解决办法吗？遇到同样的问题

EsptouchTaskParameter 这个文件 你换个端口试试

**Comment by linux-liu** [comment]
换成什么端口

**Comment by XuXiangJun** [comment]
> 换成什么端口

随便什么端口都可以，不过设备端的回复目标端口不跟着做修改的话，会导致设备连上路由器了但APP收不到回复

**Comment by linux-liu** [comment]
> > 换成什么端口
> 
> 随便什么端口都可以，不过设备端的回复目标端口不跟着做修改的话，会导致设备连上路由器了但APP收不到回复

 mPortListening = 18266;
        mTargetPort = 7001;这两个端口都要换吗

**Comment by XuXiangJun** [comment]
只要改 mPortListening 就行了

**Comment by linux-liu** [comment]
> 只要改 mPortListening 就行了

我发现我改了还是没用，还是一样的错误
D/__EsptouchTask: send gc code 
2020-04-13 11:00:19.935 19575-19790/com.espressif.iot_esptouch_demo D/__EsptouchTask: send gc code 
2020-04-13 11:00:25.939 19575-19790/com.espressif.iot_esptouch_demo D/__EsptouchTask: send gc code 
2020-04-13 11:00:31.939 19575-19790/com.espressif.iot_esptouch_demo D/__EsptouchTask: send gc code 
2020-04-13 11:00:37.940 19575-19790/com.espressif.iot_esptouch_demo D/__EsptouchTask: send gc code 
2020-04-13 11:00:55.967 19575-19793/com.espressif.iot_esptouch_demo W/System.err:     at com.espressif.iot.esptouch.task.__EsptouchTask$1.run(__EsptouchTask.java:167)
2020-04-13 11:00:55.967 19575-19793/com.espressif.iot_esptouch_demo I/__EsptouchTask: receive rubbish message, just ignore
2020-04-13 11:00:55.968 19575-19793/com.espressif.iot_esptouch_demo D/__EsptouchTask: __listenAsyn() finish

**Comment by XuXiangJun** [comment]
> receive rubbish message, just ignore

收到的数据不对啊，设备那边有修改过回复内容吗？

**Comment by linux-liu** [comment]
> > receive rubbish message, just ignore
> 
> 收到的数据不对啊，设备那边有修改过回复内容吗？

设备端只调用了三个函数
esp_wifi_set_mode(WIFI_MODE_STA);
	esp_smartconfig_set_type(SC_TYPE_ESPTOUCH);

	if(esp_smartconfig_start(sc_callback)== ESP_OK)
	{
		printf("smartconfig_start success\n");
	}

**Comment by linux-liu** [comment]
> > receive rubbish message, just ignore
> 
> 收到的数据不对啊，设备那边有修改过回复内容吗？
还需要修改啥

**Comment by XuXiangJun** [comment]
> > > receive rubbish message, just ignore
> > 
> > 
> > 收到的数据不对啊，设备那边有修改过回复内容吗？
> 
> 设备端只调用了三个函数
> esp_wifi_set_mode(WIFI_MODE_STA);
> esp_smartconfig_set_type(SC_TYPE_ESPTOUCH);
> 
> ```
> if(esp_smartconfig_start(sc_callback)== ESP_OK)
> {
> 	printf("smartconfig_start success\n");
> }
> ```

设备那边有没有成功连上路由器知道吗？

**Comment by linux-liu** [comment]
> > > > receive rubbish message, just ignore
> > > 
> > > 
> > > 收到的数据不对啊，设备那边有修改过回复内容吗？
> > 
> > 
> > 设备端只调用了三个函数
> > esp_wifi_set_mode(WIFI_MODE_STA);
> > esp_smartconfig_set_type(SC_TYPE_ESPTOUCH);
> > ```
> > if(esp_smartconfig_start(sc_callback)== ESP_OK)
> > {
> > 	printf("smartconfig_start success\n");
> > }
> > ```
> 
> 设备那边有没有成功连上路由器知道吗？

没有连上吧。连上了不是配网成功了。我这个华为荣耀20 android 10.0会出现这个问题。其他9.0 、8.0、7.0没有问题

**Comment by XuXiangJun** [comment]
如果你改了 APP 这边的监听端口，而设备那边连上路由器后没有往这个端口发送回复，或者回复的格式没有按照协议来的话，APP这边也是没法知道设备的配网情况的。

**Comment by linux-liu** [comment]
> 如果你改了 APP 这边的监听端口，而设备那边连上路由器后没有往这个端口发送回复，或者回复的格式没有按照协议来的话，APP这边也是没法知道设备的配网情况的。

设备端那边说不用改端口，只要调那几个函数，不知道在哪改。

**Comment by XuXiangJun** [comment]
确实，一般情况下是不需要改这个端口号的。
因为我这边只是 APP 开发，设备端的开发并不懂，如果有设备端的疑问
Esp32 可以去这边提问:  https://github.com/espressif/esp-idf
Esp8266 去这边: https://github.com/espressif/ESP8266_RTOS_SDK

**Comment by linux-liu** [comment]
> 确实，一般情况下是不需要改这个端口号的。
> 因为我这边只是 APP 开发，设备端的开发并不懂，如果有设备端的疑问
> Esp32 可以去这边提问: https://github.com/espressif/esp-idf
> Esp8266 去这边: https://github.com/espressif/ESP8266_RTOS_SDK

嗯嗯，我用Android 10配网设备端没有收到任何消息，但用Android 更低的版本是可以的

**Comment by XuXiangJun** [comment]
这就奇怪了， Android 10 应该没有对 UDP 相关的做什么修改
你用 APP 试试看改为发 组播包(Multicast) 配网看看

**Comment by XuXiangJun** [comment]
> 嗯嗯，我用Android 10配网设备端没有收到任何消息，但用Android 更低的版本是可以的
请问你们用的是什么手机？
设备端用的是什么版本的 idf ？

**Comment by MuYuLinFeng** [comment]
mPortListening  你修改这个端口不行？

**Comment by linux-liu** [comment]
> mPortListening 你修改这个端口不行？

改成哪个，随便改吗

**Comment by linux-liu** [comment]
> > 嗯嗯，我用Android 10配网设备端没有收到任何消息，但用Android 更低的版本是可以的
> 
> 请问你们用的是什么手机？
> 设备端用的是什么版本的 idf ？
华为荣耀20，设备端用的3.3.1

**Comment by MuYuLinFeng** [comment]
我是写了个算法对这两个端口做自增

**Comment by linux-liu** [comment]
有技术群吗，我这个问题还是没解决，华为荣耀20 Android 10版本配不了网，设备端没收到打印信息，设备端没有配网成功。我安卓端发送udp一直没有收到回复，改了端口号也不行

**Comment by MuYuLinFeng** [comment]
两个端口修改都不行吗

**Comment by EspressifApp** [comment]
我建议到 idf 项目下去问问看， APP 这边 BUG 的可能性很小了
https://github.com/espressif/esp-idf
或者把设备端的版本升级到 v4.0 的版本试试
我这边华为Android 10的手机只有P30， idf v3.3.1试过是可以配上网的

**Comment by linux-liu** [comment]
> 两个端口修改都不行吗

是的，都试过了

**Comment by linux-liu** [comment]
> 我建议到 idf 项目下去问问看， APP 这边 BUG 的可能性很小了
> https://github.com/espressif/esp-idf
> 或者把设备端的版本升级到 v4.0 的版本试试
> 我这边华为Android 10的手机只有P30， idf v3.3.1试过是可以配上网的

主要设备端说只能调几个函数，源码看不到，他也不清楚怎么弄

**Comment by XuXiangJun** [comment]
> > 我建议到 idf 项目下去问问看， APP 这边 BUG 的可能性很小了
> > https://github.com/espressif/esp-idf
> > 或者把设备端的版本升级到 v4.0 的版本试试
> > 我这边华为Android 10的手机只有P30， idf v3.3.1试过是可以配上网的
> 
> 主要设备端说只能调几个函数，源码看不到，他也不清楚怎么弄

可以去 idf 下面提个 issue 看看
您这边就 荣耀20 配不上吗？其他手机能配上吗？

**Comment by linux-liu** [comment]
> > > 我建议到 idf 项目下去问问看， APP 这边 BUG 的可能性很小了
> > > https://github.com/espressif/esp-idf
> > > 或者把设备端的版本升级到 v4.0 的版本试试
> > > 我这边华为Android 10的手机只有P30， idf v3.3.1试过是可以配上网的
> > 
> > 
> > 主要设备端说只能调几个函数，源码看不到，他也不清楚怎么弄
> 
> 可以去 idf 下面提个 issue 看看
> 您这边就 荣耀20 配不上吗？其他手机能配上吗？

嗯好，还有小米8青春版也是Android 10的系统。我试过其他更低版本的手机Android 9.0 7.0是可以的

**Comment by MuYuLinFeng** [comment]
> 我们这边用 p30(Android 10) 测试下来没有问题
> 你们用的是我们的 APP 吗？
> 设备用的是 Esp32 还是 Esp8266？



> > receive rubbish message, just ignore
> 
> 收到的数据不对啊，设备那边有修改过回复内容吗？

你好 我發現我的不是端口占用引起的配网超时 这个回复内容应该是没做过修改的
不是必现 能成功配网的时候每次都会成功 ，不能成功的时候一次也不能成功
（华为mate30 pro Android10.0，emui 10.0）

I/__EsptouchTask: receive rubbish message, just ignore
D/UDPSocketServer: receiveSpecLenBytes() entrance: len = 11
I/UDPSocketClient: USPSocketClient is interrupt
I/UDPSocketServer: USPSocketServer is interrupt
W/UDPSocketServer: mServerSocket is closed

**Comment by Tingdang** [comment]
"send gc code"这个打印，看代码是不用在意的。问题是"Address already in use"这个报错，楼主是不是改代码了，重复使用一个非""255.255.255"的地址是会报这个错误的。除非socket设置setReuseAddress(true).如果改成了组播的socket,joinGroup 和leaveGroup一定要成对使用。

**Comment by zhubinsheng** [comment]
不仅华为mate30  Android10.0，mate20一样会有问题，多台手机必现的，建议你们买几台手机试试吧 emui很坑的 得多试试
